CREATE DATABASE Coorganicas;

USE Coorganicas;

/*** CRIAÇÃO DAS TABELAS COORGÂNICAS ***/

CREATE TABLE Tipo_Usuario
(
	Id_Tipo_Usuario INT IDENTITY PRIMARY KEY NOT NULL,
	Tipo VARCHAR(255) NOT NULL
);


CREATE TABLE Produto
(
	Id_Produto INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR(255) NOT NULL,
	Descricao VARCHAR(255) NOT NULL
);


CREATE TABLE Usuario
(
	Id_Usuario INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR(255) NOT NULL,
	CNPJ CHAR(14) UNIQUE NOT NULL,
	Senha VARCHAR(255) NOT NULL,
	Email VARCHAR(255) UNIQUE NOT NULL,
	Id_Tipo_Usuario INT FOREIGN KEY REFERENCES Tipo_Usuario(Id_Tipo_Usuario)
);


CREATE TABLE Telefone
(
	Id_Telefone INT IDENTITY PRIMARY KEY NOT NULL,
	Telefone VARCHAR(255),
	Id_Usuario INT FOREIGN KEY REFERENCES Usuario(Id_Usuario)
);

CREATE TABLE Receita
(
	Id_Receita INT IDENTITY PRIMARY KEY NOT NULL,
	Titulo VARCHAR(255) NOT NULL,
	Conteudo TEXT NOT NULL,
	Id_Usuario INT FOREIGN KEY REFERENCES Usuario(Id_Usuario)
);


CREATE TABLE Endereco
(
	Id_Endereco INT IDENTITY PRIMARY KEY NOT NULL,
	Cep CHAR(8) NOT NULL,
	Endereco VARCHAR(255) NOT NULL,
	Numero INT,
	Id_Usuario INT FOREIGN KEY REFERENCES Usuario(Id_Usuario)
);

CREATE TABLE Oferta
(
	Id_Oferta INT IDENTITY PRIMARY KEY NOT NULL,
	Preco MONEY NOT NULL,
	Cidade VARCHAR(255) NOT NULL,
	Validade DATE NOT NULL,
	Quantidade FLOAT NOT NULL,
	Regiao VARCHAR(255) NOT NULL,
	Id_Usuario INT FOREIGN KEY REFERENCES Usuario(Id_Usuario),
	Id_Produto INT FOREIGN KEY REFERENCES Produto(Id_Produto)
);

CREATE TABLE Reserva
(
	Id_Reserva INT IDENTITY PRIMARY KEY NOT NULL,
	Data_Reserva DATETIME DEFAULT GETDATE() NOT NULL,
	Quantidade FLOAT NOT NULL,
	Data_Espera DATETIME,
	Status_Reserva VARCHAR(255) NOT NULL,
	Id_Usuario INT FOREIGN KEY REFERENCES Usuario(Id_Usuario),
	Id_Oferta INT FOREIGN KEY REFERENCES Oferta(Id_Oferta)

);

/*** CRIAÇÃO DAS TABELAS COORGÂNICAS ***/
